apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apic-ingress-ca
  namespace: cp4i-apic
spec:
  commonName: ingress-ca
  duration: 87600h0m0s
  isCA: true
  issuerRef:
    kind: Issuer
    name: apic-self-signed
  renewBefore: 720h0m0s
  privateKey:
    rotationPolicy: Always
  secretName: apic-ingress-ca
